spring:
  thymeleaf:
    cache: false
  datasource:
    url: ${DB}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:/schema.sql
      mode: always
